# Generated by Django 3.2 on 2021-05-12 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_number',
            new_name='accountnumber',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_type',
            new_name='accounttype',
        ),
    ]
