# Generated by Django 3.2 on 2021-05-12 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_auto_20210512_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accountnumber',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='accounttype',
            new_name='account_type',
        ),
    ]
